# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityFcmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm', models.CharField(blank=True, max_length=512, null=True)),
                ('city_id', models.ForeignKey(db_column='CityData.id', on_delete=django.db.models.deletion.CASCADE, to='city.CityData')),
                ('user_id', models.ForeignKey(db_column='UserData.mobile', on_delete=django.db.models.deletion.CASCADE, to='register.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='UserCityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.ForeignKey(db_column='CityData.id', on_delete=django.db.models.deletion.CASCADE, to='city.CityData')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.UserData')),
            ],
        ),
    ]
