# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercitydata',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercitydata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.UserData'),
        ),
    ]
