# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20170406_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercitydata',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='register.UserData'),
        ),
    ]
