# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdata',
            name='shop_id',
            field=models.ForeignKey(db_column='ShopData.shop_id', on_delete=django.db.models.deletion.CASCADE, to='shop.ShopData'),
        ),
    ]
