# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20170331_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdata',
            name='expiry_date',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerdata',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
