# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170331_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdata',
            name='mobile',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='password',
            field=models.CharField(help_text='Use\'[algo]$[salt]$[hexdigest]\' or usethe < ahref ="password/">change password form</a>.', max_length=128, verbose_name='password'),
        ),
    ]
