# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170331_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdata',
            name='id',
        ),
        migrations.AddField(
            model_name='shopdata',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='mobile',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
