# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170512_1449'),
        ('shop', '0005_auto_20170413_1707'),
    ]

    operations = [
    ]
