# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopdata_subscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='subscription_expiry_date',
            field=models.DateTimeField(default=datetime.date(2017, 5, 19)),
        ),
    ]
