# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20161219_1758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image_data',
            new_name='WelcomeData',
        ),
    ]
