# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myoffers', '0002_delete_offer_bought_data'),
    ]

    operations = [
    ]
